Error: always set an error code
Error helper has been expanded to recognise and set various error codes
with default of 500; numerous 4XX errors in the codebase have been
rewritten to use the helper; numerous error messages about missing
values have been updated to supply a 400 code; JavaScript has been
stripped of the isError() helper because ajax request errors will now
always result in something other than 200 OK so there’s no further need
for the magic words kludge.