Error: resend header if transparent compression is on
Cleaning the buffer will erase the header outputted by transparent compression, so we need to resend it.