Error: changes to error_snitcher() and error() functions
Fixed bitwise conditional in error_snitcher(); removed ob_get_level()
check in error() – no longer required; disabling E_USER_NOTICE when
setting default error reporting level; stripping tags from the $title
instead of escaping in error().