Error: changes to error and exception handlers
Removed error_panicker() because error() does plain text reporting if
TESTER; added two exception handlers to match the two remaining error
handlers; error reporting is not reduced if JAVASCRIPT – makes no
sense, we already have display_errors off to avoid puking into the
output stream; modified error() to also report in plain text if
JAVASCRIPT.