Error: removed snitcher functions, and other changes
All error are hard stops – we can’t continue after a caught Exception
anyway, so this only affects error handling of low severity error
levels; stripping tags from the logged message for better readability;
removed throwable type hint; decide error reporting level based on
DEBUG only (which installer and upgrader set to true).